name: Publish
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '25'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: publish.yml
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew build publish publishMods -x check --stacktrace --no-configuration-cache
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
